name: Deploy Frontend to GCP VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build frontend Docker image
      run: |
        cd Crudfrontend
        docker build -t frontend-image .

    - name: Copy Docker image to GCP VM via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "Crudfrontend"
        target: "~/app"

    - name: Run frontend container on GCP VM via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          cd ~/app/Crudfrontend
          docker stop frontend-container || true
          docker rm frontend-container || true
          docker build -t frontend-image .
          docker run -d --name frontend-container -p 80:80 frontend-image
